### ISSUE TITLE
Regarding camera pose data

### ISSUE THREAD

**Issue by SoohwanSong** [VIS4ROB-lab/aerial-depth-completion#3]
I found this work very interesting. 
Especially, this benchmark dataset is very useful. Thank you!
I want to test my view selection algorithm on this benchmark dataset,
but I cannot get the camera poses of all images and ground truth 3D models.
Could you upload the camera pose data and ground truth 3D models on this page?
Thank you again!

**Comment by weblucas** [comment]
The camera poses are also inside the h5 files. The models are been processed, but if you want to access before the public release, just send me an email.

**Comment by weblucas** [comment]
The models are already public.  So I am closing the issue
